# Generated by Django 3.2 on 2022-08-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер аккаунта')),
                ('account_type', models.IntegerField(default=1, verbose_name='Тип аккаунта')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('citizenship', models.TextField(default='кыргызстан', verbose_name='Гражданство')),
                ('birth_year', models.DateField(verbose_name='Дата рождения')),
                ('work_place', models.TextField(blank=True, null=True, verbose_name='Место работы')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сума кредита')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата получения кредита')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.account', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'loans',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.client', verbose_name='Клиент'),
        ),
    ]
